services:

  db:
    image: postgres:18
    restart: always
    shm_size: 128mb
    env_file:
      - .env

    environment:
      POSTGRES_DB: address
      POSTGRES_USER: papu
      POSTGRES_PASSWORD: 12345678

    ports:
      - "5437:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always

    ports:
      - "8080:8080"

volumes:
  postgres_data: