export enum OrderStatusCode {
  CREATED = 'PENDIENTE',
  ACCEPTED = 'APROBADO',
  PREPARING = 'ENVIADO',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED'
};
