export enum OrderStatusCode {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  SENDING = 'SENDING',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}
